### ISSUE TITLE
Filter for zero candles

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/trading-strategy#141]
### Background

On 21-12-2023 some of the candles for [this pair](https://tradingstrategy.ai/trading-view/polygon/uniswap-v3/eth-usdc-fee-5#1h) have values of zero for all of OHLC. This is causing errors for visualisation (due to division by zero when calculating percentage change). 

Can also be seen on daily candles. 

![Image](https://github.com/tradingstrategy-ai/trading-strategy/assets/74208897/4fce51db-a7b9-4f54-985f-32be1ecf6619)

**Comment by AlexTheLion123** [comment]
@miohtama How should filter work? Forward fill?

**Comment by miohtama** [comment]
- @hieuh25 find the root cause and add `assert` in the production to not to make zero candles
- @AlexTheLion123 add a default filter to `tradingstrategy` package to filter out there candles
